### ISSUE TITLE
View User Profile Details - 1

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-news-hounds#162]
As an author, I would like to see the content of a User Profile so I can read it.

**Given** a user is viewing a list of User Profiles  
**When** they select a user
**Then** they should be directed to a User Profile Detail page

User Profile Details include:

* Full name
* Avatar image (if exists, else use a default image)
* Display name
* Email
* Creation Date (MM/DD/YYYY)
* User Profile type

**Comment by gavinschriver** [comment]
**View is not specified on wireframe (probably base this on Admin User List/manager just minus controls)
-Client-side Components:
ProfileProvider - GetProfiles, GetProfileByUserId ? 
ProfileList (/profiles), individual links to -> ProfileDetail (/profiles/4)

-Server
ViewSet:
List - serialize/return all RareUsers but only with minimum info needed to populate the matching ProfileList?
Retrieve- serialized rep with all the juicy deets for a single RareUser?
