### ISSUE TITLE
View All User Profiles - 2

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-news-hounds#163]
As an admin, I would like to see a list of all the User Profiles so that I can keep track of who is using the system.

**Given** the user is an admin in the Rare application  
**When** they select the `User Profiles` menu option  
**Then** they should be directed to the User Profiles list page  
**And** each user in the list should display the full name, the display name and the user type.
**And** the list should be in ordered alphabetically by user display name  

> **Technical note:** For a user to be considered an admin, the `is_staff` property on the related Django User must be set to `True`. An efficient way to do this for the project is to create 2 user fixtures that you can use to seed your database. One user will be a regular author, and the other will be an admin.

**Comment by gavinschriver** [comment]
-lil fuzzy on how to  best"fake" users in fixtures re:  passwords; theres some magic that generates the hash value that represents what a user gives as a password, soooo do we need to manually hash a pw when we write a fixture and write down what the actual "human readable" form is?

**Comment by skratz17** [comment]
could we just copy the password from the other user fixture? since the same hasing algorithm should always be used, if we just copy the other password for a new user fixture i think we'd get a new user whose password is also "me"
