### ISSUE TITLE
Admins Can Approve Posts - 3

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-news-hounds#164]
As an admin I would like the ability to approve Posts that I deem appropriate so that the system can provide quality content.

**Comment by gavinschriver** [comment]
-may be good candidate for @action property in Post viewset, ie /posts/4/approve, which will look up that Post by its PK in the route of a PUT and then change its 'approved' value to true and save

**Comment by skratz17** [comment]
ooooh i dig that that sounds like a very good call
