### ISSUE TITLE
Author Created Posts are initially Unapproved - 1

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-news-hounds#165]
As an admin I would like Posts written by non-admin users (a.k.a. "Authors") to be initially unapproved, so that authors are unable to publish any inappropriate Posts without oversight.

> **NOTE:** If an admin writes a Post it should be automatically approved.

**Comment by gavinschriver** [comment]
-Need to change the default of 'approved' on Post model to False; in post Create method, we could look up the django user submitting the post and see if their is_staff att is True, and if so set that attribute on the new post to True 
-How do we keep track of whether a user "is staff" in a session? add another token upon authentication based on looking up that attribute for a valid authenticated user? that token allows conditional access to admin features of the site?

**Comment by skratz17** [comment]
i think i like the idea of using another like `isStaff` token... the only alternative i could really think of would be to like wrap our entire app in something like a `<UserProvider>` which just maintains the state of a single user representing the user the current user is logged in as, and then if you ever needed that info anywhere you could use that context and grab that user object.

regardless, i think we'll definitely want to make sure we implement server-side validation as thoroughly as we can for all admin-related ops... like if some server-side request handling method represents some bit of admin functionality, we need to first and foremost check if the `req.auth.user` is an admin and respond with like an HTTP 403 if they are not

**Comment by mgjeffries** [comment]
Hmm.. there is also a permissions model in the django auth.  https://docs.djangoproject.com/en/3.1/ref/contrib/auth/
